#!/usr/bin/env bash
# Updates the current state of the server
# Installs Nginx on the server
# Configures custom HTTP header X-Served-By

# Update and install nginx
apt-get -y update
apt-get install -y nginx

# Create HTML files
echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Create Nginx configuration with custom header
cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm 404.html index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$HOSTNAME;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=-VGIt10m9VQ;
    }
    location /xyz {
        return 404;
    }
    error_page 404 /404.html;
}
EOF

# Restart nginx to apply changes
service nginx restart
